// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rX8bJl2z7kIK1XpkF0cAvcYZqw950QY',
    appId: '1:1055212653669:web:fea404ca87e1cbd2ce4a8c',
    messagingSenderId: '1055212653669',
    projectId: 'leafgo-3d952',
    authDomain: 'leafgo-3d952.firebaseapp.com',
    storageBucket: 'leafgo-3d952.firebasestorage.app',
    measurementId: 'G-EGE6XP2XP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOr5YBEzbMgdJgRQ2iTRW4uAV-vXX8i3k',
    appId: '1:1055212653669:android:8ba94af6dd9934dece4a8c',
    messagingSenderId: '1055212653669',
    projectId: 'leafgo-3d952',
    storageBucket: 'leafgo-3d952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-teGu8UWUOUYL9RG8yEQPVCdUwR-9RLQ',
    appId: '1:1055212653669:ios:3baa18f64f97f021ce4a8c',
    messagingSenderId: '1055212653669',
    projectId: 'leafgo-3d952',
    storageBucket: 'leafgo-3d952.firebasestorage.app',
    iosClientId: '1055212653669-dcigm2i109p24u3lo475f0hek0fpdj9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.leafgoApp',
  );
}
